# Generated by Django 5.1.4 on 2025-01-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=25)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
