# Generated by Django 5.1.4 on 2025-01-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTCModel',
            new_name='Otc',
        ),
    ]
