# Generated by Django 5.1.4 on 2025-01-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0003_excelupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otc',
            name='code',
        ),
        migrations.AlterField(
            model_name='otc',
            name='order',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='otc',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='otc',
            name='target',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
    ]
