# Generated by Django 5.1.4 on 2025-01-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0005_orderlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='order',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=5, null=True),
        ),
    ]
