# Generated by Django 5.1.4 on 2025-01-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0006_alter_otc_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtcUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='otc_files/')),
            ],
        ),
        migrations.DeleteModel(
            name='ExcelUpload',
        ),
    ]
