# Generated by Django 5.1.4 on 2025-01-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0007_otcupload_delete_excelupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='productregist_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
