# Generated by Django 5.1.4 on 2025-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0008_productregist'),
    ]

    operations = [
        migrations.AddField(
            model_name='otc',
            name='expiry',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
