# Generated by Django 5.1.4 on 2025-01-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0009_otc_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='expiry',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='productregist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='productregist_files/'),
        ),
    ]
