# Generated by Django 5.1.4 on 2025-01-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0010_alter_otc_expiry_alter_productregist_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='otc',
            name='last',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productregist',
            name='file',
            field=models.FileField(default=1, upload_to='productregist_files/'),
            preserve_default=False,
        ),
    ]
