# Generated by Django 5.1.4 on 2025-01-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0012_alter_otc_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='expiry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
