# Generated by Django 5.1.4 on 2025-01-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('otc', '0013_alter_otc_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='otc',
            name='ingredients',
            field=models.ManyToManyField(related_name='otc_products', to='ingredient.ingredient'),
        ),
    ]
