# Generated by Django 5.1.4 on 2025-01-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0014_otc_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='otc',
            name='dosage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otc',
            name='effects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otc',
            name='precautions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
