# Generated by Django 5.1.4 on 2025-01-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('otc', '0015_otc_dosage_otc_effects_otc_precautions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='otc_products', to='ingredient.ingredient'),
        ),
    ]
