# Generated by Django 5.1.4 on 2025-01-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('otc', '0016_alter_otc_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='otc_products', to='ingredient.ingredient'),
        ),
    ]
