# Generated by Django 5.1.4 on 2025-01-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0017_alter_otc_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='otc',
            name='old_expiry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
