# Generated by Django 5.1.4 on 2025-01-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0018_otc_old_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespiryRegist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='respiryregist_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductRegist',
        ),
    ]
