# Generated by Django 5.1.4 on 2025-01-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0019_respiryregist_delete_productregist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respiryregist',
            name='file',
            field=models.FileField(upload_to='otc_respiryregist_files/'),
        ),
    ]
