# Generated by Django 5.1.4 on 2025-02-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0020_alter_respiryregist_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otcupload',
            name='file',
            field=models.FileField(upload_to='files/otc_files/'),
        ),
    ]
