# Generated by Django 5.1.4 on 2025-01-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.IntegerField()),
                ('recall', models.IntegerField(blank=True, null=True)),
                ('completion', models.IntegerField(blank=True, null=True)),
                ('company', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('spec', models.IntegerField(blank=True, null=True)),
                ('lot', models.IntegerField(blank=True, null=True)),
                ('expiry', models.IntegerField(blank=True, null=True)),
                ('spec_num', models.IntegerField(blank=True, null=True)),
                ('unit_num', models.DecimalField(blank=True, decimal_places=1, default=False, max_digits=5, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('total_quantitiy', models.DecimalField(blank=True, decimal_places=1, default=False, max_digits=7, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=1, default=False, max_digits=15, null=True)),
            ],
        ),
    ]
