# Generated by Django 5.1.4 on 2025-01-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='total_quantitiy',
            new_name='total_quantity',
        ),
    ]
