# Generated by Django 5.1.4 on 2025-01-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_total_quantitiy_return_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='cum_price',
            field=models.DecimalField(blank=True, decimal_places=1, default=False, max_digits=17, null=True),
        ),
    ]
