# Generated by Django 5.1.4 on 2025-01-20 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_returnlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnlist',
            name='entry',
        ),
        migrations.AddField(
            model_name='returnlist',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
