# Generated by Django 5.1.4 on 2025-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_returnlist_entry_returnlist_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comp1', models.CharField(blank=True, max_length=50, null=True)),
                ('comp2', models.CharField(blank=True, max_length=50, null=True)),
                ('comp3', models.CharField(blank=True, max_length=50, null=True)),
                ('price1', models.IntegerField(blank=True, null=True)),
                ('price2', models.IntegerField(blank=True, null=True)),
                ('price3', models.IntegerField(blank=True, null=True)),
                ('price_sum', models.IntegerField(blank=True, null=True)),
                ('price_sell', models.IntegerField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
