# Generated by Django 5.1.4 on 2025-01-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='price1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='price2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='price3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='price_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='price_sum',
            field=models.IntegerField(default=0),
        ),
    ]
