# Generated by Django 5.1.4 on 2025-01-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_set_price1_alter_set_price2_alter_set_price3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('bill_10k', models.IntegerField(default=0)),
                ('bill_5k', models.IntegerField(default=0)),
                ('bill_1k', models.IntegerField(default=0)),
                ('otc_in', models.IntegerField(default=0)),
                ('otc_discount', models.IntegerField(default=0)),
                ('otc_margin', models.IntegerField(default=0)),
                ('presc_num', models.IntegerField(default=0)),
                ('otc_num', models.IntegerField(default=0)),
                ('presc_in', models.IntegerField(default=0)),
                ('presc_bill', models.IntegerField(default=0)),
                ('presc_card', models.IntegerField(default=0)),
                ('otc_bill', models.IntegerField(default=0)),
                ('otc_card', models.IntegerField(default=0)),
                ('medicine_insur', models.IntegerField(default=0)),
                ('medicine_nonsur', models.IntegerField(default=0)),
                ('presc_insur', models.IntegerField(default=0)),
                ('presc_nonsur', models.IntegerField(default=0)),
                ('presc_sum', models.IntegerField(default=0)),
                ('card_in', models.IntegerField(default=0)),
                ('margin_sum', models.IntegerField(default=0)),
                ('presc_calc', models.IntegerField(default=0)),
                ('otc_calc', models.IntegerField(default=0)),
                ('bill_calc', models.IntegerField(default=0)),
                ('card_calc', models.IntegerField(default=0)),
            ],
        ),
    ]
