# Generated by Django 5.1.4 on 2025-01-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
