# Generated by Django 5.1.4 on 2025-01-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_profit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='date',
            field=models.IntegerField(),
        ),
    ]
