# Generated by Django 5.1.4 on 2025-01-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_profit_card_in_alter_profit_medicine_insur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='bill',
            field=models.IntegerField(default=0),
        ),
    ]
