# Generated by Django 5.1.4 on 2025-01-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_profit_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='amount_billing',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
