# Generated by Django 5.1.4 on 2025-01-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_profit_amount_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='bill_gap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profit',
            name='card_gap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profit',
            name='otc_gap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profit',
            name='presc_gap',
            field=models.IntegerField(default=0),
        ),
    ]
