# Generated by Django 5.1.4 on 2025-01-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_profit_bill_gap_profit_card_gap_profit_otc_gap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='otc_in',
            field=models.IntegerField(blank=True),
        ),
    ]
