# Generated by Django 5.1.4 on 2025-01-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_alter_profit_otc_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='amount_billing',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='card_in',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='medicine_insur',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='medicine_nonsur',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='otc_bill',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='otc_card',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='otc_discount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='otc_margin',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='otc_num',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='presc_bill',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='presc_card',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='presc_in',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='presc_insur',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='presc_nonsur',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='presc_num',
            field=models.IntegerField(blank=True),
        ),
    ]
