# Generated by Django 5.1.4 on 2025-01-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_alter_profit_amount_billing_alter_profit_card_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='otc_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
