# Generated by Django 5.1.4 on 2025-01-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_alter_profit_amount_billing_alter_profit_card_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('must', models.CharField(max_length=100)),
                ('checkbox', models.BooleanField(default=False)),
            ],
        ),
    ]
