# Generated by Django 5.1.4 on 2025-01-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('stock', models.BooleanField(default=False)),
            ],
        ),
    ]
