# Generated by Django 5.1.4 on 2025-01-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_outofstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('payment', models.IntegerField(default=0)),
                ('card', models.CharField(max_length=20)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
