# Generated by Django 5.1.4 on 2025-01-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='datetime',
            new_name='date',
        ),
    ]
