# Generated by Django 5.1.4 on 2025-01-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_rename_datetime_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stock_files')),
            ],
        ),
    ]
