# Generated by Django 5.1.4 on 2025-01-22 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_stockupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
