# Generated by Django 5.1.4 on 2025-01-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_stockupload_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
