# Generated by Django 5.1.4 on 2025-01-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
