# Generated by Django 5.1.4 on 2025-01-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_alter_payment_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='lot',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
