# Generated by Django 5.1.4 on 2025-02-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_alter_return_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupload',
            name='file',
            field=models.FileField(upload_to='files/stock_files'),
        ),
    ]
