# Generated by Django 5.1.4 on 2025-01-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtcUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='etc_files/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RespiryRegist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='etc_respiryregist_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=False, max_digits=6)),
                ('target', models.DecimalField(decimal_places=4, default=False, max_digits=6)),
                ('order', models.DecimalField(blank=True, decimal_places=4, default=False, max_digits=6, null=True)),
                ('expiry', models.IntegerField(blank=True, null=True)),
                ('old_expiry', models.IntegerField(blank=True, null=True)),
                ('effects', models.TextField(blank=True, null=True)),
                ('dosage', models.TextField(blank=True, null=True)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='etc_products', to='ingredient.ingredient')),
            ],
        ),
    ]
