# Generated by Django 5.1.4 on 2025-01-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etc',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etc',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
