# Generated by Django 5.1.4 on 2025-01-27 08:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0002_alter_etc_code_alter_etc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etc',
            name='order',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='etc',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='etc',
            name='target',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
    ]
