# Generated by Django 5.1.4 on 2025-02-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0003_alter_etc_order_alter_etc_quantity_alter_etc_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etcupload',
            name='file',
            field=models.FileField(upload_to='files/etc_files/'),
        ),
        migrations.AlterField(
            model_name='respiryregist',
            name='file',
            field=models.FileField(upload_to='files/etc_respiryregist_files/'),
        ),
    ]
